# Generated by Django 3.2.12 on 2022-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='Забыли написать заголовок', max_length=50, null=True),
        ),
    ]
